version: '2'
services:
    db:
        image: postgres

    web:
        build: .
        command: bundle exec bin/rails s -b 0.0.0.0 -p 3000
        volumes:
            - .:/src
        ports:
            - "3000:3000"
        depends_on:
            - db

    js:
        build:
            context: .
            dockerfile: Dockerfile-js
        command: npm run-script rwr-node-dev-server
        volumes:
            - .:/src
