# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6e3ec20addaebffd5f78c450cd7f7536af954117a7f03027dba81162055ff17b221980e2d8db4812c0b87e14693f2ff418bd62643f892f0b69df804c8c808e

test:
  secret_key_base: 69bf131ad70b15db3fc5bbf1649e68bb5527e733828c2f2667fdbc1159ce04263186fdf00917c6af9a46e11110e185bd95732838d7f10c35c979626775c4b6f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
